exports['package exported files 1'] = {
  "name": "vis-dev-utils                           ",
  "files": [
    "        LICENSE-APACHE-2.0",
    "        LICENSE-MIT",
    "        README.md",
    "        babel-preset/index.js",
    "        babel-register/index.js",
    "        babel-register/index.js.map",
    "        bin/generate-examples-index.js",
    "        bin/generate-examples-index.js.map",
    "        bin/test-e2e-interop.js",
    "        bin/test-e2e-interop.js.map",
    "        declarations/constants.d.ts",
    "        declarations/constants.d.ts.map",
    "        declarations/generate-rollup-configuration/index.d.ts",
    "        declarations/generate-rollup-configuration/index.d.ts.map",
    "        declarations/header.d.ts",
    "        declarations/header.d.ts.map",
    "        declarations/index.d.ts",
    "        declarations/index.d.ts.map",
    "        declarations/inspect-npm-pack.d.ts",
    "        declarations/inspect-npm-pack.d.ts.map",
    "        declarations/util.d.ts",
    "        declarations/util.d.ts.map",
    "        dist/assets/bundle-file.d.ts",
    "        dist/assets/bundle-index.d.ts",
    "        dist/assets/bundle-index.js",
    "        dist/assets/bundle-root.d.ts",
    "        dist/assets/bundle-root.js",
    "        dist/interop/base-config.json",
    "        dist/vis-dev-utils.cjs.js",
    "        dist/vis-dev-utils.cjs.js.map",
    "        dist/vis-dev-utils.esm.js",
    "        dist/vis-dev-utils.esm.js.map",
    "        lib/header.d.ts",
    "        lib/header.d.ts.map",
    "        lib/header.js",
    "        lib/header.js.map",
    "        lib/inspect-npm-pack.d.ts",
    "        lib/inspect-npm-pack.d.ts.map",
    "        lib/inspect-npm-pack.js",
    "        lib/inspect-npm-pack.js.map",
    "        package.json"
  ]
}
